### ISSUE TITLE
Error in chrome 64.0.3282.186 Win 10

### ISSUE THREAD

**Issue by pewien7** [cozmo/jsQR#53]
I got the following error in chrome console after a few moments (5-15min):

jsQR.js:90 Uncaught RangeError: Invalid typed array length: Infinity
    at typedArrayConstructByLength (<anonymous>)
    at new Uint8ClampedArray (native)
    at Function.BitMatrix.createEmpty (https://cozmo.github.io/jsQR/jsQR.js:90:30)
    at Object.extract (https://cozmo.github.io/jsQR/jsQR.js:9594:40)
    at jsQR (https://cozmo.github.io/jsQR/jsQR.js:337:33)
    at tick (https://cozmo.github.io/jsQR/:102:20)

Webcam keeps freezing. This happens on every laptop I use. FF has this problem also.

**Comment by cozmo** [comment]
Hmm not seen this issue before, I'll investigate. Sorry about that.

**Comment by cozmo** [comment]
@pewien7 If it was possible would you be willing to send a screenshot/dump of the frame that is causing the failure? Assuming this is causing the webcam to freeze it should be easy to capture a screenshot I think? If not no worries but could make it easier to create a reproducible test case.

**Comment by pewien7** [comment]
I found the solution. Your code is ok. The problem is navigator.mediaDevices.getUserMedia which losing connection with camera. It happens time to time. Setting lower frameRate helped. But best solution is to check if your track is 'muted' if so just restart stream. Something like that:

	  if(video.srcObject.getTracks()[0].muted)
	  {
          //here is func to restart stream
	  }

**Comment by digosts** [comment]
I made a screen where I will read several qr code in sequend, I open the reader all right and execute the tick () function, but after that if I click to read the next the camera appears on my screen more locked in the previous qrcode.

I'm using video.pause on the tick;
and video.play when it enters the screen.

**Comment by cozmo** [comment]
@digosts Does the issue persist if you do not use jsQR? That is to say if you set up the same code but don't pass the library any data/don't even include the library do you still run into the issue?

**Comment by cozmo** [comment]
Closing due to lack of activity - If you still have questions please comment/re-open and I'd be happy to help.

**Comment by cozmo** [comment]
Hey so it turns out our code did have an issue that was causing the "Invalid typed array length: Infinity" which has been fixed in version `1.0.6`. I don't think this is necessarily related to the video pausing playing stuff, but either way it's been fixed.
